HamnavaKala/Areas/Admin/Controllers/CategoryController.cs
using HamnavaKala.Core.Interfaces;
using HamnavaKala.DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HamnavaKala.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _category;
        public CategoryController(ICategoryService category)
        {
            _category = category;
        }
        public IActionResult ShowAllCategory()
        {
            return View(_category.ShowAllCategory());
        }

        [HttpGet]
        public IActionResult AddCategory(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        public IActionResult AddCategory(Category cat)
        {
            if (!ModelState.IsValid)
            {
                return View(cat);
            }
            if (_category.ExistCategory(cat.CategoryFaName, cat.CategoryEnName,0))
            {
                ModelState.AddModelError("CategoryEnName", "دسته بندی تکراری میباشد.");
                return View(cat);
            }
            int res = _category.AddCategory(cat);
            TempData["Result"] = res > 0 ? "true" : "false";
            return RedirectToAction(nameof(ShowAllCategory));
        }

        [HttpGet]
        public IActionResult ShowAllSubCategory(int id)
        {
            ViewBag.id = id;
            return View(_category.ShowAllsubcategory(id));
        }

        [HttpGet]
        public IActionResult ShowAllSubsubCategory(int id)
        {
            ViewBag.id = id;
            return View(_category.ShowAllsubcategory(id));
        }

        [HttpGet]
        public IActionResult UpdateCategory(int id)
        {
            Category cat = _category.GetCategoryById(id);
            if (cat == null)
            {
                return NotFound();
            }
            return PartialView("_updateCategory",cat);
        }

        [HttpPost]
        public IActionResult UpdateCategory(Category cat)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(ShowAllCategory));
            }
            if (_category.ExistCategory(cat.CategoryFaName, cat.CategoryEnName, cat.CategoryId))
            {
                return Json(5);
            }
            bool res = _category.UpdateCategory(cat);
            int sendJson = res ? 2 : 4;
            return Json(sendJson);
        }

        [HttpGet]
        public IActionResult DeleteCategory(int id)
        {
            Category cat = _category.GetCategoryById(id);
            if (cat == null)
            {
                return NotFound();
            }
            return PartialView("_DeleteCategory",cat);
        }

        [HttpPost]
        public IActionResult DeleteCategory(Category cat)
        {
            cat.IsDelete = true;
            bool grid = _category.UpdateCategory(cat);
            int sendJson = grid ? 3 : 4;
            return Json(sendJson);
            
        }
    }
}

HamnavaKala/Areas/Admin/Controllers/GuranteeController.cs
using HamnavaKala.Core.Interfaces;
using HamnavaKala.DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HamnavaKala.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GuranteeController : Controller
    {
        private readonly IGurantee _gurantee;
        public GuranteeController(IGurantee gurantee)
        {
            _gurantee = gurantee;
        }
        public IActionResult ShowGurantee()
        {
            return View(_gurantee.showAllGurantee());
        }

        [HttpGet]
        public IActionResult AddGurantee()
        {
            return PartialView("_AddGurantee");
        }

        [HttpPost]
        public IActionResult AddGurantee(ProductGurantee gurantee)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(ShowGurantee));
            }
            if (_gurantee.ExistGurantee(gurantee.GuranteeName, 0))
            {
                return Json(5);
            }
            int grid = _gurantee.AddGurantee(gurantee);
            int sendJson = grid > 0 ? 1 : 4;
            return Json(sendJson);
        }

        [HttpGet]
        public IActionResult UpdateGurantee(int id)
        {
            ProductGurantee gurantee = _gurantee.GetGuranteebyId(id);
            return PartialView("_UpdateGurantee", gurantee);
        }

        [HttpPost]
        public IActionResult UpdateGurantee(ProductGurantee gurantee)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(ShowGurantee));
            }
            if (_gurantee.ExistGurantee(gurantee.GuranteeName, 0))
            {
                return Json(5);
            }
            bool grid = _gurantee.UpdateGurantee(gurantee);
            int sendJson = grid ? 2 : 4;
            return Json(sendJson);
        }

        [HttpGet]
        public IActionResult DeleteGurantee(int id)
        {
            ProductGurantee gurantee = _gurantee.GetGuranteebyId(id);
             return PartialView("_DeleteGurantee", gurantee);
        }

        [HttpPost]
        public IActionResult DeleteGurantee(ProductGurantee gurantee)
        {
           
            bool grid = _gurantee.DeleteGurantee(gurantee);
            int sendJson = grid ? 3 : 4;
            return Json(sendJson);
        }
    }
}

HamnavaKala/Areas/Admin/Controllers/SliderController.cs
using HamnavaKala.Core.Classes;
using HamnavaKala.Core.Interfaces;
using HamnavaKala.DataLayer.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HamnavaKala.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly ISlider _context;
        public SliderController(ISlider context)
        {
            _context = context;
        }
        public IActionResult Index(int page =1)
        {
            ViewBag.page = page;
            ViewBag.SliderCount = _context.SliderCount();
            return View(_context.ShowSlider(page));
        }

        [HttpGet]
        public IActionResult AddSlider()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSlider(Slider slider, IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                return View(slider);
            }
            if (file == null)
            {
                ModelState.AddModelError("ImgSlider", "لطفا یک عکس برای سلایدر انتخاب نمایید");
                return View(slider);
            }
            string imgname = uploadImg.CreateImg(file, "slider-main");
            if (imgname == "flase")
            {
                TempData["Result"] = "failed";
                return RedirectToAction(nameof(Index));
            }

            slider.ImgSlider = imgname;
            int res = _context.AddSlider(slider);
            TempData["Result"] = res > 0 ? "success" : "failed";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult UpdateSlider(int id)
        {
            Slider slider = _context.GetSliderById(id);
            if (slider == null)
            {
                TempData["NotFound"] = "NotFound";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(slider);
            }
        }

        [HttpPost]
        public IActionResult UpdateSlider(Slider slider,IFormFile file)
        {
            if (!ModelState.IsValid)
            {
                return View(slider);
            }
            if (file != null)
            {
                string imgname = uploadImg.CreateImg(file, "slider-main");
                if (imgname == "false")
                {
                    TempData["Result"] = "failed";
                    return RedirectToAction(nameof(Index));
                }
                bool DeleteImage = uploadImg.DeleteImg("slider-main", slider.ImgSlider);
                if (!DeleteImage)
                {
                    TempData["Result"] = "failed";
                    return RedirectToAction(nameof(Index));
                }
                slider.ImgSlider = imgname;
            }


                bool res = _context.UpdateSlider(slider);
                TempData["Result"] = res  ? "success" : "failed";
                return RedirectToAction(nameof(Index));
            
        }

        [HttpGet]
        public IActionResult DeleteSlider(int id)
        {
            Slider slider = _context.GetSliderById(id);
            if (slider == null)
            {
                TempData["NotFound"] = "NotFound";
                return RedirectToAction(nameof(Index));
            }
            return PartialView("_deleteSlider",slider);
        }

        [HttpPost]
        public IActionResult DeleteSlider(Slider slider, IFormFile file)
        {

            bool DeleteImage = uploadImg.DeleteImg("slider-main", slider.ImgSlider);
            if (!DeleteImage)
            {
                TempData["Result"] = "failed";
                return RedirectToAction(nameof(Index));
            }
            bool res = _context.DeleteSlider(slider);
            int sendJson = res ? 3 : 4;
            return Json(sendJson);
        }
    }
}

HamnavaKala/Controllers/ProductController.cs
using HamnavaKala.Core.Interfaces;
using HamnavaKala.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HamnavaKala.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductServices _product;
        public ProductController(IProductServices product)
        {
            _product = product;
        }
        public IActionResult ProductDetails(int id)
        {
            var d = _product.ShowDetailsProduct(id);
            ViewBag.Property = _product.showViewforProduct(id);
            ViewBag.Gallery = _product.ShowGallery(id);
            return View(d);
        }

        public IActionResult ShowReview(int id)
        {
            var review = _product.Findreviewbyproduct(id);
            return View(review);
        }

        public IActionResult ShowAllProperty(int id)
        {
            return View(_product.ShowAllPropertyforProduct(id));
        }

        public IActionResult ShowCommentsForProduct(int id)
        {
            return View(_product.ShowuserCommentsForProduct(id));
        }

        public IActionResult ShowAllFaq(int id)
        {
            return View(_product.ShowallQuestionAnswer(id));
        }

        [Route("compare/{id?}/{id2?}/{id3?}")]
        public IActionResult Compare(int id, int? id2, int? id3)
        {
            List<int?> Listid = new List<int?> { id, id2, id3 };

            if (id <= 0 )
            {
                return RedirectToAction("Index", "Home");
            }
            var ListProduct = _product.Showcompareproduct(Listid);

            var productgroup = ListProduct.GroupBy(p => p.productid).Select(p => new comapreviewmodel
            {
                categoryid = p.FirstOrDefault().categoryid,
                productfatitle = p.FirstOrDefault().productfatitle,
                productid = p.Key,
                productimg = p.FirstOrDefault().productimg,
                productprice = p.FirstOrDefault().productprice,
                Compareviewmodel = p.FirstOrDefault().Compareviewmodel,

            }).ToList();

            ViewBag.property = _product.ShowPropertyCompare(productgroup[0].categoryid);
            ViewBag.Product = _product.GetProductForCompare(productgroup[0].categoryid, Listid);
            return View(productgroup.OrderBy(p => p.productid));

        }
    }
}

HamnavaKala/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="~/AdminPanel/assets/images/favicon.ico">

    <title>آقای ادمین | قالب واکنشگرا مدیریتی</title>

    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="~/AdminPanel/assets/plugins/morris/morris.css">

    <!-- App css -->
    <link href="~/AdminPanel/assets/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="~/AdminPanel/assets/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/AdminPanel/assets/js/modernizr.min.js"></script>

</head>


<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">

            <!-- LOGO -->
            <div class="topbar-left">
                <a href="index.html" class="logo"><span>آقای<span>ادمین</span></span><i class="zmdi zmdi-layers"></i></a>
            </div>

            <!-- Button mobile view to collapse sidebar menu -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container">

                    <!-- Page title -->
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <button class="button-menu-mobile open-left">
                                <i class="zmdi zmdi-menu"></i>
                            </button>
                        </li>
                        <li>
                            <h4 class="page-title">داشبورد</h4>
                        </li>
                    </ul>

                    <!-- Right(Notification and Searchbox -->
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <!-- Notification -->
                            <div class="notification-box">
                                <ul class="list-inline m-b-0">
                                    <li>
                                        <a href="javascript:void(0);" class="right-bar-toggle">
                                            <i class="zmdi zmdi-notifications-none"></i>
                                        </a>
                                        <div class="noti-dot">
                                            <span class="dot"></span>
                                            <span class="pulse"></span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Notification bar -->
                        </li>
                        <li class="hidden-xs">
                            <form role="search" class="app-search">
                                <input type="text" placeholder="به دنبال چه می گردی ؟؟؟"
                                       class="form-control">
                                <a href=""><i class="fa fa-search"></i></a>
                            </form>
                        </li>
                    </ul>

                </div><!-- end container -->
            </div>

            <!-- end navbar -->
        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        <partial name="_AdminSideMenu" />
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            @RenderBody()
            <!-- content -->

            <footer class="footer">
                آقای ادمین2016 ©.
            </footer>

        </div>


        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <div class="side-bar right-bar">
            <a href="javascript:void(0);" class="right-bar-toggle">
                <i class="zmdi zmdi-close-circle-o"></i>
            </a>
            <h4 class="">اعلانات</h4>
            <div class="notification-list nicescroll">
                <ul class="list-group list-no-border user-list">
                    <li class="list-group-item">
                        <a href="#" class="user-list-item">
                            <div class="avatar">
                                <img src="~/AdminPanel/assets/images/users/avatar-2.jpg" alt="">
                            </div>
                            <div class="user-desc">
                                <span class="name">کاربر شماره یک</span>
                                <span class="desc">متن کاربر شماره یک</span>
                                <span class="time">2 ساعت قبل</span>
                            </div>
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" class="user-list-item">
                            <div class="icon bg-info">
                                <i class="zmdi zmdi-account"></i>
                            </div>
                            <div class="user-desc">
                                <span class="name">ثبت نام جدید</span>
                                <span class="desc">کاربری جدید در سایت ثبت نام کرده است</span>
                                <span class="time">5 ساعت قبل</span>
                            </div>
                        </a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" class="user-list-item">
                            <div class="icon bg-pink">
                                <i class="zmdi zmdi-comment"></i>
                            </div>
                            <div class="user-desc">
                                <span class="name">پیام جدید</span>
                                <span class="desc">متن پیام جدید از کاریی جدید</span>
                                <span class="time">1 روز قبل</span>
                            </div>
                        </a>
                    </li>
                    <li class="list-group-item active">
                        <a href="#" class="user-list-item">
                            <div class="avatar">
                                <img src="~/AdminPanel/assets/images/users/avatar-3.jpg" alt="">
                            </div>
                            <div class="user-desc">
                                <span class="name">کاربر شماره 2</span>
                                <span class="desc">با سلام من یک متن کاملا آزمایشی هستم</span>
                                <span class="time">2 روز قبل</span>
                            </div>
                        </a>
                    </li>
                    <li class="list-group-item active">
                        <a href="#" class="user-list-item">
                            <div class="icon bg-warning">
                                <i class="zmdi zmdi-settings"></i>
                            </div>
                            <div class="user-desc">
                                <span class="name">تنظیمات</span>
                                <span class="desc">تنظیمات جدید برای دسترسی و راحتی شما موجود است</span>
                                <span class="time">1 روز قبل</span>
                            </div>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
        <!-- /Right-bar -->

    </div>
    <!-- END wrapper -->



    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="~/AdminPanel/assets/js/jquery.min.js"></script>
    <script src="~/AdminPanel/assets/js/bootstrap-rtl.min.js"></script>
    <script src="~/AdminPanel/assets/js/detect.js"></script>
    <script src="~/AdminPanel/assets/js/fastclick.js"></script>
    <script src="~/AdminPanel/assets/js/jquery.blockUI.js"></script>
    <script src="~/AdminPanel/assets/js/waves.js"></script>
    <script src="~/AdminPanel/assets/js/jquery.nicescroll.js"></script>
    <script src="~/AdminPanel/assets/js/jquery.slimscroll.js"></script>
    <script src="~/AdminPanel/assets/js/jquery.scrollTo.min.js"></script>

    <!-- KNOB JS -->
    <!--[if IE]>
    <script type="text/javascript" src="~/AdminPanel/assets/plugins/jquery-knob/excanvas.js"></script>
    <![endif]-->
    <script src="~/AdminPanel/assets/plugins/jquery-knob/jquery.knob.js"></script>

    <!--Morris Chart-->
    <script src="~/AdminPanel/assets/plugins/morris/morris.min.js"></script>
    <script src="~/AdminPanel/assets/plugins/raphael/raphael-min.js"></script>

    <!-- Dashboard init -->
    <script src="~/AdminPanel/assets/pages/jquery.dashboard.js"></script>

    <!-- App js -->
    <script src="~/AdminPanel/assets/js/jquery.core.js"></script>
    <script src="~/AdminPanel/assets/js/jquery.app.js"></script>

    <!--Sweet alert and validation for modal-->
    <script src="~/Site/assets/js/jquery.validate.min.js"></script>
    <script src="~/Site/assets/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Site/assets/js/SweetAlert.js"></script>
    <script src="~/Site/assets/js/OpenModal.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>

HamnavaKala/Areas/Admin/Views/Shared/_AdminSideMenu.cshtml
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">

        <!-- User -->
        <div class="user-box">
            <div class="user-img">
                <img src="~/AdminPanel/assets/images/users/avatar-1.jpg" alt="user-img" title="Mat Helme" class="img-circle img-thumbnail img-responsive">
                <div class="user-status offline"><i class="zmdi zmdi-dot-circle"></i></div>
            </div>
            <h5><a href="#">علی یدالهی</a> </h5>
            <ul class="list-inline">
                <li>
                    <a href="#">
                        <i class="zmdi zmdi-settings"></i>
                    </a>
                </li>

                <li>
                    <a href="#" class="text-custom">
                        <i class="zmdi zmdi-power"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- End User -->
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">دسته بندی ها</li>

                <li>
                    <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="waves-effect active"><i class="zmdi zmdi-view-dashboard"></i> <span> داشبورد </span> </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Product" asp-action="showproduct" class="waves-effect active"><i class="zmdi zmdi-view-dashboard"></i> <span> محصولات </span> </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Slider" asp-action="Index" class="waves-effect"><i class="zmdi zmdi-collection-image"></i> <span>  سلایدر </span> </a>
                </li>

                <li>
                    <a asp-area="Admin" asp-controller="Product" asp-action="ShowProductColor" class="waves-effect"><i class="zmdi zmdi-colorize"></i> <span>  رنگ محصول </span> </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Category" asp-action="ShowAllCategory" class="waves-effect"><i class="zmdi zmdi-steam"></i> <span>  دسته بندی ها </span> </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Gurantee" asp-action="ShowGurantee" class="waves-effect"><i class="zmdi zmdi-gamepad"></i> <span>    گارانتی ها </span> </a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="product" asp-action="showProperties" class="waves-effect"><i class="zmdi zmdi-folder-special"></i> <span>    خصوصیات ها </span> </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> رابط کاربی </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled">
                        <li><a href="ui-buttons.html">دکمه ها</a></li>
                        <li><a href="ui-cards.html">کارد</a></li>
                        <li><a href="ui-draggable-cards.html">کارت های جابه جا شونده</a></li>
                        <li><a href="ui-checkbox-radio.html">چک باکس ها</a></li>
                        <li><a href="ui-material-icons.html">آیکون های طراحی متریال</a></li>
                        <li><a href="ui-font-awesome-icons.html">فونت آسوم</a></li>
                        <li><a href="ui-themify-icons.html">تم فی آیکون</a></li>
                        <li><a href="ui-modals.html">مدل ها</a></li>
                        <li><a href="ui-notification.html">اطلاعات</a></li>
                        <li><a href="ui-range-slider.html">نوار تغیرات</a></li>
                        <li><a href="ui-components.html">اجزا</a>
                        <li><a href="ui-sweetalert.html">هشدار ها</a>
                        <li><a href="ui-treeview.html">نمایش درختی</a>
                        <li><a href="ui-widgets.html">ویجت ها</a></li>
                    </ul>
                </li>



            </ul>
            <div class="clearfix"></div>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>

</div>

HamnavaKala/Areas/Admin/Views/Shared/_MainModal.cshtml
<div id="MainModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content" id="ModalContent">



        </div>
    </div>
</div>